# app/config/security.yml
security:
    providers:
        commercetools:
           id: commercetools.user_provider
#        in_memory:
#            memory:
#               users:
#                  yaron:
#                     password: yaron
#                     roles: ROLE_USER
#                  admin:
#                     password: admin
#                     roles: ROLE_ADMIN
    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
        Commercetools\Symfony\CtpBundle\Security\User\User: plaintext

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: example
            anonymous: ~
            commercetools_login:
              login_path: login
              check_path: login_check
              default_target_path: _ctp_example
            logout:
              path: logout
              target: _ctp_example
#        default:
#            anonymous: ~

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/_ctp/example/user, roles: [ROLE_USER, ROLE_ADMIN] }
