_ctp_example:
    path:     /example/product
    defaults: { _controller: CtpBundle:Catalog:index }

_ctp_example_product:
    path:    /example/product/{slug}
    defaults: { _controller: CtpBundle:Catalog:detail }

login:
    path: /example/login
    defaults: { _controller: CtpBundle:User:login }
login_check:
    path: /example/login_check
logout:
    path: /example/logout

_ctp_example_user:
    path:    /example/user
    defaults: { _controller: CtpBundle:User:index }

_ctp_example_cart:
    path: /example/cart
    defaults: { _controller: CtpBundle:Cart:index}

